import { Schema, model } from "mongoose";
import type { IUserSettings, IOrganizationSettings, IVendorSettings } from "./settings.types.js";

const userSchema = new Schema<IUserSettings>({ userId: { type: Schema.Types.ObjectId, ref: "User", unique: true, required: true }, language: { type: String, default: "en" }, timezone: { type: String, default: "UTC" }, dateFormat: { type: String, enum: ["DD/MM/YYYY", "MM/DD/YYYY", "YYYY-MM-DD"], default: "YYYY-MM-DD" }, timeFormat: { type: String, enum: ["12h", "24h"], default: "24h" }, accessibility: { reducedMotion: { type: Boolean, default: false }, highContrast: { type: Boolean, default: false }, screenReaderAnnouncements: { type: Boolean, default: true } } }, { timestamps: true });
const organizationSchema = new Schema<IOrganizationSettings>({ organizationId: { type: Schema.Types.ObjectId, ref: "Organization", unique: true, required: true }, timezone: { type: String, default: "UTC" }, locale: { type: String, default: "en-NG" }, currency: { type: String, default: "NGN", uppercase: true }, defaultWorkOrderPriority: { type: String, enum: ["low", "medium", "high", "critical"], default: "medium" }, defaultServiceRequestPriority: { type: String, enum: ["low", "medium", "high", "critical"], default: "medium" }, notificationPolicies: { type: Map, of: Boolean, default: {} } }, { timestamps: true });
const vendorSchema = new Schema<IVendorSettings>({ vendorId: { type: Schema.Types.ObjectId, ref: "Vendor", unique: true, required: true }, timezone: { type: String, default: "UTC" }, locale: { type: String, default: "en-NG" }, marketplaceAvailable: { type: Boolean, default: true }, profileVisible: { type: Boolean, default: true }, autoApply: { type: Boolean, default: false }, minimumAnnualContractValue: { type: Number, min: 0 }, maximumDistanceKm: { type: Number, min: 0 }, contractTypes: { pm: { type: Boolean, default: true }, emergency: { type: Boolean, default: true }, modernization: { type: Boolean, default: false }, audits: { type: Boolean, default: true } } }, { timestamps: true });
export const UserSettings = model<IUserSettings>("UserSettings", userSchema);
export const OrganizationSettings = model<IOrganizationSettings>("OrganizationSettings", organizationSchema);
export const VendorSettings = model<IVendorSettings>("VendorSettings", vendorSchema);
