import { Schema, model, type Document, type Types } from "mongoose";
import type { PMOccurrenceApprovalState, PMOccurrenceStatus, PMAssignment, PMAssignmentChange } from "./pm.types.js";
export interface IPMOccurrence extends Document { organizationId: Types.ObjectId; preventiveMaintenanceId: Types.ObjectId; facilityId: Types.ObjectId; locationId: Types.ObjectId; assetId: Types.ObjectId; scheduledAt: Date; status: PMOccurrenceStatus; approvalState: PMOccurrenceApprovalState; assignment?: PMAssignment; assignmentHistory: PMAssignmentChange[]; approvedBy?: Types.ObjectId; approvedAt?: Date; rejectionReason?: string; rejectedBy?: Types.ObjectId; rejectedAt?: Date; workOrderId?: Types.ObjectId; createdBy: Types.ObjectId; createdAt: Date; updatedAt: Date }
const assignmentSchema = new Schema({ targetType: { type: String, enum: ["user", "vendor", "team"], required: true }, targetId: { type: Schema.Types.ObjectId, required: true }, assignedAt: { type: Date, required: true }, assignedBy: { type: Schema.Types.ObjectId, ref: "User", required: true } }, { _id: false });
const assignmentChangeSchema = new Schema({ action: { type: String, enum: ["assigned", "reassigned", "cleared"], required: true }, previousTargetType: String, previousTargetId: Schema.Types.ObjectId, targetType: String, targetId: Schema.Types.ObjectId, actorId: { type: Schema.Types.ObjectId, ref: "User", required: true }, occurredAt: { type: Date, required: true } }, { _id: false });
const schema = new Schema<IPMOccurrence>({ organizationId: { type: Schema.Types.ObjectId, ref: "Organization", required: true, index: true }, preventiveMaintenanceId: { type: Schema.Types.ObjectId, ref: "PMPlan", required: true, index: true }, facilityId: { type: Schema.Types.ObjectId, ref: "Facility", required: true }, locationId: { type: Schema.Types.ObjectId, ref: "Location", required: true }, assetId: { type: Schema.Types.ObjectId, ref: "Asset", required: true }, scheduledAt: { type: Date, required: true }, status: { type: String, enum: ["scheduled", "generated", "completed", "cancelled"], default: "scheduled" }, approvalState: { type: String, enum: ["pending_approval", "approved", "rejected"], required: true }, assignment: assignmentSchema, assignmentHistory: { type: [assignmentChangeSchema], default: [] }, approvedBy: { type: Schema.Types.ObjectId, ref: "User" }, approvedAt: Date, rejectionReason: String, rejectedBy: { type: Schema.Types.ObjectId, ref: "User" }, rejectedAt: Date, workOrderId: { type: Schema.Types.ObjectId, ref: "WorkOrder" }, createdBy: { type: Schema.Types.ObjectId, ref: "User", required: true } }, { timestamps: true });
schema.index({ preventiveMaintenanceId: 1, scheduledAt: 1 }, { unique: true });
schema.index({ workOrderId: 1 }, { unique: true, sparse: true });
schema.index({ organizationId: 1, scheduledAt: 1, status: 1, approvalState: 1 });
export const PMOccurrence = model<IPMOccurrence>("PMOccurrence", schema);
