import { Schema, model, type Document, type Types } from "mongoose";
import type { PMStatus, PMOccurrenceStatus, PMRecurrenceConfig, PMAssignment, PMAssignmentChange } from "./pm.types.js";
export interface IPMPlan extends Document { organizationId: Types.ObjectId; facilityId: Types.ObjectId; locationId: Types.ObjectId; assetId: Types.ObjectId; title: string; description: string; maintenanceType: string; frequency?: string; recurrence?: PMRecurrenceConfig; defaultAssignment?: PMAssignment; assignmentHistory: PMAssignmentChange[]; isActive: boolean; plannedDate: Date; /** @deprecated Execution dates belong to PMOccurrence. Retained for legacy records/API compatibility. */ occurrenceDate?: Date; priority: "low" | "medium" | "high" | "critical"; checklist: { label: string; required: boolean }[]; instructions?: string; estimatedDurationMinutes?: number; status: PMStatus; /** @deprecated Execution status belongs to PMOccurrence. */ occurrenceStatus?: PMOccurrenceStatus; createdBy: Types.ObjectId; approvedBy?: Types.ObjectId; approvedAt?: Date; rejectionReason?: string; rejectedBy?: Types.ObjectId; rejectedAt?: Date; /** @deprecated Work Order linkage belongs to PMOccurrence. */ workOrderId?: Types.ObjectId; skipHistory?: { skippedAt: Date; skippedBy: Types.ObjectId; originalDueDate: Date; reason?: string }[] }
const recurrenceSchema = new Schema({ frequency: { type: String, enum: ["daily", "weekly", "monthly", "yearly", "interval"], required: true }, interval: { type: Number, min: 1, required: true }, startDate: { type: Date, required: true }, endDate: Date, weekdays: [{ type: Number, min: 0, max: 6 }], monthDay: { type: Number, min: 1, max: 31 } }, { _id: false });
const assignmentSchema = new Schema({ targetType: { type: String, enum: ["user", "vendor", "team"], required: true }, targetId: { type: Schema.Types.ObjectId, required: true }, assignedAt: { type: Date, required: true }, assignedBy: { type: Schema.Types.ObjectId, ref: "User", required: true } }, { _id: false });
const assignmentChangeSchema = new Schema({ action: { type: String, enum: ["assigned", "reassigned", "cleared"], required: true }, previousTargetType: String, previousTargetId: Schema.Types.ObjectId, targetType: String, targetId: Schema.Types.ObjectId, actorId: { type: Schema.Types.ObjectId, ref: "User", required: true }, occurredAt: { type: Date, required: true } }, { _id: false });
const schema = new Schema<IPMPlan>({ organizationId: { type: Schema.Types.ObjectId, ref: "Organization", required: true, index: true }, facilityId: { type: Schema.Types.ObjectId, ref: "Facility", required: true }, locationId: { type: Schema.Types.ObjectId, ref: "Location", required: true }, assetId: { type: Schema.Types.ObjectId, ref: "Asset", required: true }, title: { type: String, required: true }, description: { type: String, required: true }, maintenanceType: { type: String, required: true }, frequency: String, recurrence: recurrenceSchema, defaultAssignment: assignmentSchema, assignmentHistory: { type: [assignmentChangeSchema], default: [] }, isActive: { type: Boolean, default: true }, plannedDate: { type: Date, required: true }, occurrenceDate: { type: Date }, priority: { type: String, enum: ["low", "medium", "high", "critical"], required: true }, checklist: [{ label: String, required: Boolean }], instructions: String, estimatedDurationMinutes: Number, status: { type: String, enum: ["pending_approval", "approved", "rejected", "cancelled"], required: true }, occurrenceStatus: { type: String, enum: ["scheduled", "generated", "completed", "cancelled"] }, createdBy: { type: Schema.Types.ObjectId, ref: "User", required: true }, approvedBy: { type: Schema.Types.ObjectId, ref: "User" }, approvedAt: Date, rejectionReason: String, rejectedBy: { type: Schema.Types.ObjectId, ref: "User" }, rejectedAt: Date, workOrderId: { type: Schema.Types.ObjectId, ref: "WorkOrder" }, skipHistory: [{ skippedAt: { type: Date, default: Date.now }, skippedBy: { type: Schema.Types.ObjectId, ref: "User", required: true }, originalDueDate: { type: Date, required: true }, reason: String }] }, { timestamps: true });
schema.index({ organizationId: 1, assetId: 1, occurrenceDate: 1 }, { unique: true, sparse: true });
export const PMPlan = model<IPMPlan>("PMPlan", schema);
