import type { EmailLayoutVariant } from "../types/communication.types.js";

const escape = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] ?? char);
export function renderBrandedEmail(input: { title: string; body: string; preheader?: string; action?: { label: string; url: string }; variant?: EmailLayoutVariant; organizationName?: string }): string {
  const accent = input.variant === "security" ? "#4f46e5" : input.variant === "alert" ? "#dc2626" : "#f97316";
  const action = input.action
    ? `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:30px 0 8px"><tr><td bgcolor="${accent}" style="border-radius:8px"><a href="${escape(input.action.url)}" style="display:inline-block;padding:14px 24px;color:#fff;text-decoration:none;font-size:14px;font-weight:700;line-height:20px">${escape(input.action.label)}</a></td></tr></table>`
    : "";
  const context = input.organizationName ? `<p style="margin:0 0 24px;color:#64748b;font-size:13px">Workspace: <strong style="color:#334155">${escape(input.organizationName)}</strong></p>` : "";
  const logoUrl = process.env.EMAIL_LOGO_URL || `${process.env.FRONTEND_URL || process.env.CLIENT_URL || "http://localhost:3000"}/logo-light.png`;
  const logo = `<img src="${escape(logoUrl)}" width="146" alt="MaintainPro" style="display:block;width:146px;height:auto;max-height:34px;object-fit:contain;object-position:left center" />`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(input.title)}</title><style>body{margin:0;background:#f1f5f9;color:#172033;font-family:Arial,Helvetica,sans-serif}a{color:${accent}}@media(max-width:620px){.frame{padding:16px!important}.content{padding:28px 22px!important}.header{padding:20px 22px!important}}</style></head><body><div style="display:none;max-height:0;overflow:hidden;opacity:0">${escape(input.preheader ?? input.title)}&nbsp;&zwnj;</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td class="frame" align="center" style="padding:40px 16px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:600px"><tr><td class="header" style="padding:24px 30px;background:#0f172a;border-radius:12px 12px 0 0"><table role="presentation" width="100%"><tr><td>${logo}</td><td align="right" style="font-size:11px;color:#94a3b8">OPERATIONS PLATFORM</td></tr></table></td></tr><tr><td class="content" style="padding:38px 42px;background:#fff;border:1px solid #e2e8f0;border-top:0"><div style="width:42px;height:4px;border-radius:4px;background:${accent};margin-bottom:24px"></div><h1 style="margin:0 0 12px;color:#0f172a;font-size:26px;line-height:34px;letter-spacing:-.5px">${escape(input.title)}</h1>${context}<div style="color:#475569;font-size:15px;line-height:25px">${input.body}</div>${action}<p style="margin:28px 0 0;color:#94a3b8;font-size:12px;line-height:19px">If the button does not work, copy and paste the link from this email into your browser.</p></td></tr><tr><td style="padding:22px 30px;background:#f8fafc;border:1px solid #e2e8f0;border-top:0;border-radius:0 0 12px 12px"><p style="margin:0 0 8px;color:#475569;font-size:12px;font-weight:700">MaintainPro</p><p style="margin:0;color:#94a3b8;font-size:11px;line-height:18px">Reliable maintenance operations for organizations and service providers.</p><p style="margin:12px 0 0;color:#cbd5e1;font-size:11px">This is an automated message. Please do not reply directly.</p></td></tr></table></td></tr></table></body></html>`;
}
