import { Types } from "mongoose";
import { AuthorizationException, ConflictException, NotFoundException } from "@/shared/errors/index.js";
import { ROLES } from "@/shared/constants/roles.js";
import { MarketplaceGeographicPolicy, type IMarketplaceGeographicPolicy } from "./marketplace-geographic-policy.model.js";
import type { GeographicPolicyInput, GeographicPolicyUpdateInput } from "./marketplace-geographic-policy.schema.js";
type Actor = { userId: string; role: string; organizationId?: string };
const managers = [ROLES.ADMIN, ROLES.FACILITY_MANAGER];
export class MarketplaceGeographicPolicyService { private organization(actor: Actor) { if (!actor.organizationId) throw new AuthorizationException("Organization context required"); return actor.organizationId; } private authorize(actor: Actor) { if (!managers.includes(actor.role as typeof managers[number])) throw new AuthorizationException("Only admin or facility manager can manage marketplace geographic policies"); }
  async list(actor: Actor) { const organizationId = this.organization(actor); const data = await MarketplaceGeographicPolicy.find({ organizationId }).sort({ priority: 1 }).limit(100); return { success: true, message: "Marketplace geographic policies retrieved successfully", data: data.map((policy) => this.toResponse(policy)) }; }
  async get(id: string, actor: Actor) { const organizationId = this.organization(actor); const policy = await MarketplaceGeographicPolicy.findOne({ _id: id, organizationId }); if (!policy) throw new NotFoundException("Marketplace geographic policy not found"); return { success: true, message: "Marketplace geographic policy retrieved successfully", data: this.toResponse(policy) }; }
  async create(input: GeographicPolicyInput, actor: Actor) { this.authorize(actor); const organizationId = this.organization(actor); if (input.enabled && await MarketplaceGeographicPolicy.exists({ organizationId, priority: input.priority, enabled: true })) throw new ConflictException("An active policy already exists for this priority"); if (input.enabled) await this.validateOrdering(organizationId, input.priority, input.maxDistanceKm); const policy = await MarketplaceGeographicPolicy.create({ ...input, organizationId: new Types.ObjectId(organizationId), createdBy: new Types.ObjectId(actor.userId) }); return { success: true, message: "Marketplace geographic policy created", data: this.toResponse(policy) }; }
  async update(id: string, input: GeographicPolicyUpdateInput, actor: Actor) { this.authorize(actor); const organizationId = this.organization(actor); const existing = await MarketplaceGeographicPolicy.findOne({ _id: id, organizationId }); if (!existing) throw new NotFoundException("Marketplace geographic policy not found"); if (input.enabled && await MarketplaceGeographicPolicy.exists({ _id: { $ne: id }, organizationId, priority: input.priority ?? existing.priority, enabled: true })) throw new ConflictException("An active policy already exists for this priority"); if (input.enabled) await this.validateOrdering(organizationId, input.priority ?? existing.priority, input.maxDistanceKm ?? existing.maxDistanceKm, id); const updated = await MarketplaceGeographicPolicy.findOneAndUpdate({ _id: id, organizationId }, { ...input, updatedBy: new Types.ObjectId(actor.userId) }, { new: true }); return { success: true, message: "Marketplace geographic policy updated", data: this.toResponse(updated!) }; }
  async setEnabled(id: string, enabled: boolean, actor: Actor) { this.authorize(actor); const organizationId = this.organization(actor); const existing = await MarketplaceGeographicPolicy.findOne({ _id: id, organizationId }); if (!existing) throw new NotFoundException("Marketplace geographic policy not found"); if (enabled) { if (await MarketplaceGeographicPolicy.exists({ _id: { $ne: id }, organizationId, priority: existing.priority, enabled: true })) throw new ConflictException("An active policy already exists for this priority"); await this.validateOrdering(organizationId, existing.priority, existing.maxDistanceKm, id); } const updated = await MarketplaceGeographicPolicy.findOneAndUpdate({ _id: id, organizationId }, { enabled, updatedBy: new Types.ObjectId(actor.userId) }, { new: true }); return { success: true, message: enabled ? "Marketplace geographic policy activated" : "Marketplace geographic policy deactivated", data: this.toResponse(updated!) }; }
  async resolve(organizationId: Types.ObjectId, priority: string) { const policy = await MarketplaceGeographicPolicy.findOne({ organizationId, priority: priority as "low" | "medium" | "high" | "critical", enabled: true }); return policy?.maxDistanceKm; }
  private async validateOrdering(organizationId: string, priority: string, distance: number, ignoreId?: string) { const policies = await MarketplaceGeographicPolicy.find({ organizationId, enabled: true, ...(ignoreId ? { _id: { $ne: ignoreId } } : {}) }).limit(4); const values: Record<string, number> = Object.fromEntries(policies.map((policy) => [policy.priority, policy.maxDistanceKm])); values[priority] = distance; const ordered: Array<[string, string]> = [["critical", "high"], ["high", "medium"], ["medium", "low"]]; for (const [strict, broad] of ordered) if (values[strict] !== undefined && values[broad] !== undefined && values[strict] > values[broad]) throw new ConflictException("Critical and higher-priority policies must be at least as geographically strict as lower-priority policies"); }
  private toResponse(policy: IMarketplaceGeographicPolicy) { return { id: policy._id.toString(), organizationId: policy.organizationId.toString(), priority: policy.priority, maxDistanceKm: policy.maxDistanceKm, enabled: policy.enabled, createdBy: policy.createdBy.toString(), updatedBy: policy.updatedBy?.toString(), createdAt: policy.createdAt.toISOString(), updatedAt: policy.updatedAt.toISOString() }; }
}
